routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('manage')->middleware('auth')->group(function(){
    Route::get('/', 'ManageController@index');
    Route::get('/dashboard', 'ManageController@dashboard')->name('manage.dashboard');
    Route::resource('/users', 'UserController');
    Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
    Route::resource('/roles', 'RoleController', ['except' => 'destroy']);
    Route::resource('/posts', 'PostsController');
    Route::resource('/categories', 'CategoriesController');

});

Route::get('/', 'PagesController@index')->name('welcome');
Route::get('/email', 'PagesController@email')->name('email');
Route::post('/email', 'PagesController@sendEmail')->name('send.email');
Route::post('/contact', 'PagesController@sendEmail')->name('send.email');
Route::get('/contact', 'PagesController@contact')->name('contact');
Route::get('/errors', 'PagesController@errors')->name('errors');
Route::get('/my-account', 'Auth\MyAccountController@show')->name('my.account');
Route::post('/my-account', 'Auth\MyAccountController@update')->name('my.account.update');
Route::delete('/my-account', 'Auth\MyAccountController@delete')->name('delete.link');

Auth::routes();

Route::resource('tags', 'TagsController', ['only' => [
     'store', 'destroy']]);

Route::post('comments', ['as'=>'comments.store', 'uses' => 'CommentsController@store']);
Route::delete('comments', ['as'=>'comments.delete', 'uses' => 'CommentsController@destroy']);

Route::get('blog/search', ['as' => 'blog.search', 'uses' => 'BlogController@search']);
Route::get('blog/{slug}', ['as' => 'blog.show', 'uses' => 'BlogController@show']);
Route::get('blog/category/{category_id}', ['as' => 'blog.category', 'uses' => 'BlogController@category']);
Route::get('blog/category/{category_id}/filter/{filter}', ['as' => 'blog.category.filtered', 'uses' => 'BlogController@categoryFiltered']);

Route::get('blog', ['as' => 'blog.index', 'uses' => 'BlogController@index']);
Route::get('blog/filtered/{filter}', ['as' => 'blog.index.filtered', 'uses' => 'BlogController@indexFiltered']);

resources/views/partials/_form-errors.blade.php
@if($errors->has($field))

    @if(!isset($type))
        {{-- Not a horizontal form --}}
        <span class="help is-danger">{{ $errors->first($field) }}</span>
    @else

        <div class="control is-horizontal">
            <div class="control-label">
                <!--spacer-->
            </div>
            <div class="control is-horizontal">
                <p class="control is-fullwidth help is-danger">
                    {{ $errors->first($field) }}
                </p>
            </div>
        </div>

    @endif

@endif

resources/views/partials/_manage.blade.php
<div class="side-menu" id="admin-side-menu">
    <aside class="menu">
        <p class="menu-label">
            General
        </p>
        <ul class="menu-list">
            <li><a href="{{route('manage.dashboard')}}" class="{{Nav::isRoute('manage.dashboard')}}">Statistics</a></li>
        </ul>
        <p class="menu-label">
            Content
        </p>
        <ul class="menu-list">
            <li><a class="has-submenu {{Nav::hasSegment(['posts'], 2)}}">Posts</a>
                <ul class="submenu">
                    <li><a href="{{route('posts.create')}}" class="{{Nav::isRoute('posts.create')}}"><span class="icon"><i class="fas fa-plus"></i></span><span> New post</span></a></li>
                    <li><a href="{{route('posts.index')}}" class="{{Nav::isRoute(['posts.index', 'posts.edit', 'posts.show'])}}">{{Laratrust::can('publish-post') ? 'All posts' : 'My posts'}} & drafts</a></li>
                </ul>
            </li>
            <li><a {{Laratrust::can('read-category') ? "href=" . route('categories.index') : ''}} class="{{Nav::isResource('categories')}} {{Laratrust::can('read-category') ? "" : 'deactivated'}}">Categories</a></li>
        </ul>
        <p class="menu-label">
            Administration
        </p>
        <ul class="menu-list">
            <li><a {{Laratrust::can('read-users') ? "href=" . route('users.index') : ''}}  class="{{Nav::isResource('users')}} {{Laratrust::can('read-users') ? '' : 'deactivated'}}">Manage users</a></li>
            <li><a class="{{(Laratrust::can('read-roles')||Laratrust::can('read-permission')) ? 'has-submenu' : 'deactivated'}} {{Nav::hasSegment(['roles', 'permissions'], 2)}}">Roles and permissions</a>
                <ul class="submenu">
                    <li><a {{Laratrust::can('read-roles') ? "href=" . route('roles.index') : ''}} class="{{Nav::isResource('roles')}} second-lvl {{Laratrust::can('read-roles') ? '' : 'deactivated'}}">Roles</a></li>
                    <li><a {{Laratrust::can('read-permission') ? "href=" . route('permissions.index') : ''}} class="{{Nav::isResource('permissions')}} second-lvl {{Laratrust::can('read-permission') ? '' : 'deactivated'}}">Permissions</a></li>
                </ul>
            </li>
        </ul>
    </aside>
</div>

resources/views/partials/_messages.blade.php
{{--@if(Session::has('success'))--}}

       {{--<template>--}}
           {{--<section>--}}
               {{--<b-notification type="is-success" has-icon>--}}
                   {{--<strong>Success: </strong>{{ Session::get('success') }}--}}
               {{--</b-notification>--}}
           {{--</section>--}}
       {{--</template>--}}

{{--@endif--}}
@if (session('status'))

        <template>
            <section>
                <b-notification type="is-success" has-icon>
                    <strong>Success: </strong>{{ session('status') }}
                </b-notification>
            </section>
        </template>

@endif

@if(count($errors)>0)

        <template>
            <section>
                <b-notification type="is-danger" has-icon>
                    <ul>Errors:</ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </b-notification>
            </section>
        </template>


@endif

resources/views/partials/_navbar.blade.php
<nav class="navbar has-shadow">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item is-paddingless" href="{{route('welcome')}}">
                <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
            </a>
            @if (Request::segment(1) == "manage")
                <a class="navbar-item is-hidden-desktop" id="admin-slideout-button">
                    <span class="icon"><i class="fa fa-arrow-alt-circle-right"></i></span>
                </a>
            @endif

            <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="navbarExampleTransparentExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item is-tab {{ Request::is('blog'.'*') ? 'is-active' : '' }}" href="{{ route('blog.index') }}">
                    Blog
                </a>
                <a class="navbar-item is-tab {{ Request::is('email') ? 'is-active' : '' }}" href="{{ route('email') }}">
                    Email
                </a>
                <a class="navbar-item is-tab {{ Request::is('contact') ? 'is-active' : '' }}" href="{{ route('contact') }}">
                    Contact
                </a>
                {{--<div class="navbar-item has-dropdown is-hoverable">--}}
                {{--<a class="navbar-link" href="/documentation/overview/start/">--}}
                {{--Docs--}}
                {{--</a>--}}
                {{--<div class="navbar-dropdown is-boxed">--}}
                {{--<a class="navbar-item" href="/documentation/overview/start/">--}}
                {{--Overview--}}
                {{--</a>--}}
                {{--<a class="navbar-item" href="https://bulma.io/documentation/modifiers/syntax/">--}}
                {{--Modifiers--}}
                {{--</a>--}}
                {{--<a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">--}}
                {{--Columns--}}
                {{--</a>--}}
                {{--<a class="navbar-item" href="https://bulma.io/documentation/layout/container/">--}}
                {{--Layout--}}
                {{--</a>--}}
                {{--<a class="navbar-item" href="https://bulma.io/documentation/form/general/">--}}
                {{--Form--}}
                {{--</a>--}}
                {{--<hr class="navbar-divider">--}}
                {{--<a class="navbar-item" href="https://bulma.io/documentation/elements/box/">--}}
                {{--Elements--}}
                {{--</a>--}}
                {{--<a class="navbar-item is-active" href="https://bulma.io/documentation/components/breadcrumb/">--}}
                {{--Components--}}
                {{--</a>--}}
                {{--</div>--}}

            </div>

            @guest
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a class="button" href="{{ route('register') }}">
                      <span class="icon">
                        <i class="fas fa-user-plus"></i>
                      </span>
                                <span>
                        Register
                      </span>
                            </a>
                        </p>
                        <p class="control">
                            <a class="button is-primary" href="{{ route('login') }}">
                      <span class="icon">
                        <i class="fas fa-sign-in-alt"></i>
                      </span>
                                <span>Login</span>
                            </a>
                        </p>
                    </div>
                </div>
            @else
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link has-dropdown is-hoverable">
                        Hi, {{ Auth::user()->name }}
                    </a>

                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item"  href="{{ route('my.account') }}">
                            My account
                        </a>
                        <a class="navbar-item" href="{{ route('manage.dashboard') }}">
                            Manage
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </div>
                </div>
            @endguest
        </div>
    </div>

</nav>